spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5439/flyway_example
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl